# Generated by Django 5.0.6 on 2024-11-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_count',
            field=models.IntegerField(default=0),
        ),
    ]
