# Generated by Django 5.0.6 on 2024-11-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
